Adding more github resources
mozilla/open-leadership-training-series pull request #59
Opened 2017-01-23 18:35 UTC by Shruti9520

2017-01-23 22:22 UTC, abbycabs requested changes
This looks amazing except for the one extra file. Maybe we should add *~ to .gitignore?

Thanks for your work here @Shruti9520!

2017-01-23 22:22 UTC, acabunoc commented on _articles/get-your-project-online/project-set-up-for-collaboration-with-github.md~
> +---
Hey @Shruti9520! It looks like this file was commit by mistake. Can you remove this from your PR?

2017-01-24 03:15 UTC, Shruti9520 commented
@acabunoc I have deleted that extra file.

2017-01-25 14:14 UTC, Shruti9520 commented
@acabunoc Do I need to make other changes in this?

2017-01-26 19:58 UTC, abbycabs approved these changes

2017-01-26 19:58 UTC, merged

2017-01-26 19:58 UTC, acabunoc commented
Thanks @Shruti9520!