Allow for Subtitles to be added to embedded videos
mozilla/open-leadership-training-series pull request #98
Opened 2019-02-19 14:53 UTC by marcwalsh

This allows for subtitles to be added to videos, but adding a variable for the TRACK tag in videowrapper.html.

Also adding subtitle file for the Open Canvas video - starting to solve #81.

@acabunoc could you review and test this for me please?

2019-02-19 19:30 UTC, abbycabs requested changes

2019-02-19 19:30 UTC, abbycabs commented on subs/OpenCanvas-Subs-EN.vtt
> + - So that's it! Get started! All you need to is print this off, get a pen fill it out.
I say 'So' a lot...

2019-02-19 19:30 UTC, acabunoc commented on _includes/videowrapper.html
> +    <track src="{{ include.subs }}" kind="subtitles" srclang="en" label="English">
```suggestion
    <track src="{{ site.baseurl }}/{{ include.subs }}" kind="subtitles" srclang="en" label="English">
```

2019-02-19 19:30 UTC, acabunoc commented on _articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas.md
> +  subs="https://mozilla.github.io/open-leadership-training-series/subs/OpenCanvas-Subs-EN.vtt"
```suggestion
  subs="/subs/OpenCanvas-Subs-EN.vtt"
```

2019-02-19 19:30 UTC, acabunoc commented on _includes/videowrapper.html
> +    <track src="{{ include.subs }}" kind="subtitles" srclang="en" label="English">
Adding this here removes the need to provide the full path for each video AND it lets us test it locally beforehand

2019-02-19 19:30 UTC, acabunoc commented on _articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas.md
> +  subs="https://mozilla.github.io/open-leadership-training-series/subs/OpenCanvas-Subs-EN.vtt"
Removed the full path and moved to videowrapper

2019-02-20 11:13 UTC, marcwalsh commented on subs/OpenCanvas-Subs-EN.vtt
> + - So that's it! Get started! All you need to is print this off, get a pen fill it out.
I'm always the same whenever I type up a conversation I've had!

2019-02-20 11:15 UTC, marcwalsh commented
Thanks @acabunoc - I've added the changes you've requested!

Hopefully this is good to merge

2019-02-20 15:31 UTC, merged